version: "3.4"

services:
  docker-discord-logger:
    container_name: docker-discord-logger
    build: .
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=Container1:Container2:Container3
      - WEBHOOK_URL=https://discord.com/api/webhooks/1389227339296149606/pQHCWkc5JMzjXnEBozzIcVLxd9rkF62NiRl4rmGFlMZyqokahOjzyXH2KgF8-OogGLX_
    restart: unless-stopped
